---

- name: Install udev rules for persistent block device names
  copy:
    src: "{{ role_path }}/files/70-ec2-nvme-devices.rules"
    dest: /etc/udev/rules.d
    owner: root
    group: root
    mode: '0644'

- name: Install NVME namespace identifier script
  copy:
    src: "{{ role_path }}/files/ec2nvme-nsid"
    dest: /usr/lib/udev
    owner: root
    group: root
    mode: '0755'

- name: Install NVME device identifier script
  copy:
    src: "{{ role_path }}/files/ebsnvme-id"
    dest: /sbin
    owner: root
    group: root
    mode: '0755'
