---

- name: Install udev rules for persistent block device names
  copy:
    src: "{{ role_path }}/files/70-ec2-nvme-devices.rules"
    dest: /etc/udev/rules.d
    owner: root
    group: root
    mode: '0644'
  notify:
    - Replay kernel device events

- name: Install NVME namespace identifier script
  copy:
    src: "{{ role_path }}/files/ec2nvme-nsid"
    dest: /usr/lib/udev
    owner: root
    group: root
    mode: '0755'
  notify:
    - Replay kernel device events

- name: Install Python 2.x NVME device identifier script
  copy:
    src: "{{ role_path }}/files/ebsnvme-id-python2.7"
    dest: /sbin/ebsnvme-id
    owner: root
    group: root
    mode: '0755'
  when:
    - ansible_python_version is version('2', '>=')
    - ansible_python_version is version('3', '<')
  notify:
    - Replay kernel device events

- name: Install Python 3.x NVME device identifier script
  copy:
    src: "{{ role_path }}/files/ebsnvme-id-python3"
    dest: /sbin/ebsnvme-id
    owner: root
    group: root
    mode: '0755'
  when:
    - ansible_python_version is version('3', '>=')
    - ansible_python_version is version('4', '<')
  notify:
    - Replay kernel device events

- name: Ensure symbolic links are created for connected devices
  meta: flush_handlers
